apiVersion: v1
kind: Pod
metadata:
  name: avr128da48-cnano-bootloader-melody
spec:
  containers:
    - name: avr128da48-cnano-bootloader-melody-xc8-mplabx
      image: artifacts.microchip.com:7999/microchip/citd/bundles/xc8-mplabx:latest
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 1
          memory: 4Gi
        limits:
          cpu: 2
          memory: 8Gi
    - name: avr128da48-cnano-bootloader-melody-gcc-mplabx
      image: artifacts.microchip.com:7999/microchip/citd/bundles/avr8-mplabx:latest
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 1
          memory: 4Gi
        limits:
          cpu: 2
          memory: 8Gi